/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WTPlayerMain */

#ifndef _Included_WTPlayerMain
#define _Included_WTPlayerMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WTPlayerMain
 * Method:    setPathForWtNativeLoader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WTPlayerMain_setPathForWtNativeLoader
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
